### PR TITLE
add Redmi Note 12 Pro (sweet_k6a) and fix failed builds

### PR DESCRIPTION
**Pull request by Vilez0**
- update broken pmbootstrap git link
- update kernel version to the default v6.8.3 for [sm7150-mainline/linux](https://github.com/sm7150-mainline/linux)
- use 256 boot_size instead of 128
- Create new device: Redmi Note 12 Pro

### CODE REVIEW

**Comment by Gelbpunkt** [comment]
You'll have to add the sweet_k6a build to the workflow as well

**Comment by Vilez0** [comment]
oh, i forgot about that :D

**Comment by Vilez0** [comment]
> You'll have to add the sweet_k6a build to the workflow as well

Done

**Comment by JIaxyga** [comment]
lgtm

**Comment by JIaxyga** [comment]
Merged, thanks

**Comment by Gelbpunkt** [comment]
> Merged, thanks

Won't work yet. It currently uses master branch of our pmaports, which needs updating.

**Pull request merged**
